using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Bunker.Models.Init_Models
{
    class Init_Health
    {
        private Specifications specifications;
        public Init_Health(Specifications _specifications)
        {
            specifications = _specifications;
            Fill_Health();
        }

        private void Fill_Health()
        {
            specifications.Health.Add("Полностью здоров");
            specifications.Health.Add("Абфракция");
            specifications.Health.Add("Аденоиды");
            specifications.Health.Add("Аллергический ринит(Хронический)");
            specifications.Health.Add("Анальный миаз");
            specifications.Health.Add("Аргентинская геморрагическая лихорадка");
            specifications.Health.Add("Болезнь Альцгеймера(Предеменция)");
            specifications.Health.Add("Болезнь Альцгеймера(Ранняя деменция)");
            specifications.Health.Add("Болезнь Альцгеймера(Умеренная деменция)");
            specifications.Health.Add("Болезнь Альцгеймера(Тяжёлая деменция)");
            specifications.Health.Add("Бородавчатая эпидермодисплазия(Вся левая рука)");
            specifications.Health.Add("Вирусный гепатит(Врождённый вирусный гепатит)");
            specifications.Health.Add("Вирусный гепатит(Острый вирусный гепатит)");
            specifications.Health.Add("Вирусный гепатит(Первично-хронический вирусный гепатит)");
            specifications.Health.Add("Вирусный гепатит(Вторично-хронический вирусный гепатит)");
            specifications.Health.Add("Височная эпилепсия");
            specifications.Health.Add("Волосяной лишай");
            specifications.Health.Add("Вульводиния - женщина, закрут яичка(только что образованный) - мужчина ");
            specifications.Health.Add("Герпес (1-2 типа)");
            specifications.Health.Add("Ветрянка (Первые признаки)");
            specifications.Health.Add("Грипп (Тяжелое течение, осложнений нет)");
            specifications.Health.Add("Грыжа спины (1 стадия)");
            specifications.Health.Add("Грыжа спины (2 стадия)");
            specifications.Health.Add("Грыжа спины (3 стадия)");
            specifications.Health.Add("Грыжа спины (4 стадия)");
            specifications.Health.Add("Злокачественный нейролептический синдром (Пик болезни)");
            specifications.Health.Add("Контактный дерматит (на пыль) (легкая степень)"); 
            specifications.Health.Add("Контактный дерматит (на пыль) (среднея степень)");
            specifications.Health.Add("Контактный дерматит (на пыль) (тяжелая степень)");
            specifications.Health.Add("Конъюнктивит (Блефароконъюнктивит)");
            specifications.Health.Add("Конъюнктивит (Кератоконъюнктивит)");
            specifications.Health.Add("Конъюнктивит (Эписклерит)");
            specifications.Health.Add("Коровья оспа (Без симптомов)");
            specifications.Health.Add("Красный плоский лишай");
            specifications.Health.Add("Лимфоцитарная интерстициальная пневмония");
            specifications.Health.Add("Лучевая болезнь");
            specifications.Health.Add("Натуральная оспа");
            specifications.Health.Add("Острая лучевая болезнь");
            specifications.Health.Add("Паразитарные краниопаги (Близнец живой, занимает слот в бункере по еде и воде, зовут Волан-де-морт(из 1 фильма), по развитию 3,5 собачих лет." +
                "У Волан-де-морта запущенный синдром Туретта + Конъюнктивит (Эписклерит) и Герпес (3 типа)) сочувствую :(");
            specifications.Health.Add("Потница");
            specifications.Health.Add("Разговоры во сне");
            specifications.Health.Add("Рак губы (1 стадия)(курил не взатяг)");
            specifications.Health.Add("Рак губы (2 стадия)(курил не взатяг)");
            specifications.Health.Add("Рак губы (3 стадия)(курил не взатяг)");
            specifications.Health.Add("Рак губы (4 стадия)(курил не взатяг)");
            specifications.Health.Add("Рак поджелудочной железы (1 стадия)");
            specifications.Health.Add("Рак поджелудочной железы (2 стадия)");
            specifications.Health.Add("Рак поджелудочной железы (3 стадия)");
            specifications.Health.Add("Рак поджелудочной железы (4 стадия)");
            specifications.Health.Add("Сахарный диабет (1 - типа, легкое течение)");
            specifications.Health.Add("Сахарный диабет (1 - типа, среднея степень)");
            specifications.Health.Add("Сахарный диабет (1 - типа, тяжелое течение)");
            specifications.Health.Add("Сахарный диабет (2 - типа, легкое течение)");
            specifications.Health.Add("Сахарный диабет (2 - типа, среднея степень)");
            specifications.Health.Add("Сахарный диабет (2 - типа, тяжелое течение)");
            specifications.Health.Add("Свиной грипп (легкое течение)");
            specifications.Health.Add("Свиной грипп (среднея степень)");
            specifications.Health.Add("Свиной грипп (тяжелое течение)");
            specifications.Health.Add("Септический артрит (Начало болезни)");
            specifications.Health.Add("Заячья губа");
            specifications.Health.Add("Волчья пасть");
            specifications.Health.Add("Укорочение уздечки языка");
            specifications.Health.Add("Гинекомастия");
            specifications.Health.Add("Аносмия");
            specifications.Health.Add("Гипогонадизм - мужчина, Миома матки - женщина ");
            specifications.Health.Add("Маршевая стопа");
            specifications.Health.Add("Мицетома");
            specifications.Health.Add("Омфалит");
            specifications.Health.Add("Транспозиция внутренних органов");
            specifications.Health.Add("Отит (Хронический)");
            specifications.Health.Add("Мышечная гипотония");
            specifications.Health.Add("Синдром кошачьего крика");
            specifications.Health.Add("Синдром Ларона (Рост - 63 см, Вес - 15 кг)");
            specifications.Health.Add("Синдром Мёбиуса");
            specifications.Health.Add("Синдром Сотоса (Рост - 210 см, Вес - 130кг)");
            specifications.Health.Add("Синдром Тричера Коллинза");
            specifications.Health.Add("Токсикомания");
            specifications.Health.Add("Торсионная дистония");
            specifications.Health.Add("Хейлит");
            specifications.Health.Add("Экзостоз (легкое течение)");
            specifications.Health.Add("Экзостоз (среднея степень)");
            specifications.Health.Add("Экзостоз (тяжелое течение)");
            specifications.Health.Add("Эктродактилия (Отсутствуют все пальцы на руке и ноге)");
            specifications.Health.Add("Эктродактилия(Остался по 1 пальцу на ногах)");
            specifications.Health.Add("Аллергия (Цитрусы) (легкая степень)");
            specifications.Health.Add("Аллергия (Цитрусы) (средняя степень)");
            specifications.Health.Add("Аллергия (Цитрусы) (тяжелая степень)");
            specifications.Health.Add("Аллергия (Пыль) (легкая степень)");
            specifications.Health.Add("Аллергия (Пыль) (средняя степень)");
            specifications.Health.Add("Аллергия (Пыль) (тяжелая степень)");
            specifications.Health.Add("Аллергия (Вода) (тяжелая степень)");
            specifications.Health.Add("Аллергия (Перхоть животных) (легкая степень)");
            specifications.Health.Add("Аллергия (Перхоть животных) (средняя степень)");
            specifications.Health.Add("Аллергия (Перхоть животных) (тяжелая степень)");
            specifications.Health.Add("Косоглазие (легкая степень)");
            specifications.Health.Add("Косоглазие (средняя степень)");
            specifications.Health.Add("Косоглазие (тяжелая степень)");
            specifications.Health.Add("Нет ноги");
            specifications.Health.Add("Нет ног");
            specifications.Health.Add("Нет руки");
            specifications.Health.Add("Нет рук");
            specifications.Health.Add("Нет глаза");
            specifications.Health.Add("Слепота (легкая степень)");
            specifications.Health.Add("Слепота (средняя степень)");
            specifications.Health.Add("Слепота (тяжелая степень)");
            specifications.Health.Add("Нет пальцев на руке");
            specifications.Health.Add("Нет пальцев на ноге");
            specifications.Health.Add("Нет пальце на руках");
            specifications.Health.Add("Нет пальцев на ногах");
            specifications.Health.Add("Облысение");
            specifications.Health.Add("Астма (легкая степень)");
            specifications.Health.Add("Астма (средняя степень)");
            specifications.Health.Add("Астма (тяжелая степень)");
            specifications.Health.Add("Туберкулез (без симптомов)");
            specifications.Health.Add("Туберкулез (легкая степень)");
            specifications.Health.Add("Туберкулез (средняя степень)");
            specifications.Health.Add("Туберкулез (тяжелая степень)");
            specifications.Health.Add("Короновирус (без симптомов)");
            specifications.Health.Add("Короновирус (легкая степень)");
            specifications.Health.Add("Короновирус (средняя степень)");
            specifications.Health.Add("Короновирус (тяжелая степень)");
            specifications.Health.Add("Бесплодие");
            specifications.Health.Add("Мигрень (легкая степень)"); 
            specifications.Health.Add("Мигрень (среднея степень)");
            specifications.Health.Add("Мигрень (тяжелая степень)");
            specifications.Health.Add("Гепатит А");
            specifications.Health.Add("Гепатит B");
            specifications.Health.Add("Гепатит C");
            specifications.Health.Add("Гепатит D");
            specifications.Health.Add("Гепатит E");
            specifications.Health.Add("Гепатит G");
            specifications.Health.Add("Абсцесс ноги (легкая степень)"); 
            specifications.Health.Add("Абсцесс ноги (среднея степень)");
            specifications.Health.Add("Абсцесс ноги (тяжелая степень)");
            specifications.Health.Add("Плоскостопие 1 степень");
            specifications.Health.Add("Плоскостопие 2 степень");
            specifications.Health.Add("Плоскостопие 3 степень");
            specifications.Health.Add("Плоскостопие 4 степень");
            specifications.Health.Add("Полностью здоровый");
            specifications.Health.Add("Полностью здоровый");
            specifications.Health.Add("Полностью здоровый");
            specifications.Health.Add("Полностью здоровый");
            specifications.Health.Add("Полностью здоровый");
            specifications.Health.Add("Полностью здоровый");
            specifications.Health.Add("Полностью здоровый");
            specifications.Health.Add("Полностью здоровый");
            specifications.Health.Add("Полностью здоровый");
            specifications.Health.Add("Дрожь в конечностях");
            specifications.Health.Add("Болезнь Паркинсона 0 этап");
            specifications.Health.Add("Болезнь Паркинсона 1 этап");
            specifications.Health.Add("Болезнь Паркинсона 2 этап");
            specifications.Health.Add("Болезнь Паркинсона 3 этап");
            specifications.Health.Add("Болезнь Паркинсона 4 этап");
            specifications.Health.Add("Болезнь Паркинсона 5 этап");
            specifications.Health.Add("Биполярное расстройство (легкая степень)"); 
            specifications.Health.Add("Биполярное расстройство (среднея степень)");
            specifications.Health.Add("Биполярное расстройство (тяжелая степень)");
            specifications.Health.Add("Невроз (легкая степень)"); 
            specifications.Health.Add("Невроз (среднея степень)");
            specifications.Health.Add("Невроз (тяжелая степень)");
            specifications.Health.Add("Перелом ноги");
            specifications.Health.Add("Переломы ног");
            specifications.Health.Add("Перелом руки");
            specifications.Health.Add("Переломы рук");
            specifications.Health.Add("Гастрит (легкая степень)");
            specifications.Health.Add("Язва желудка (легкая степень)"); 
            specifications.Health.Add("Язва желудка (среднея степень)");
            specifications.Health.Add("Язва желудка (тяжелая степень)");
            specifications.Health.Add("Гастрит (среднея степень)");
            specifications.Health.Add("Гастрит (тяжелая степень)");
            specifications.Health.Add("Заикание (легкая степень)"); 
            specifications.Health.Add("Заикание (среднея степень)");
            specifications.Health.Add("Заикание (тяжелая степень)");
            specifications.Health.Add("Дефект речи (легкая степень)"); 
            specifications.Health.Add("Дефект речи (среднея степень)");
            specifications.Health.Add("Дефект речи (тяжелая степень)");
            specifications.Health.Add("Грибок ногтей (легкая степень)"); 
            specifications.Health.Add("Грибок ногтей (среднея степень)");
            specifications.Health.Add("Грибок ногтей (тяжелая степень)");
            specifications.Health.Add("Псориаз (легкая степень)"); 
            specifications.Health.Add("Псориаз (среднея степень)");
            specifications.Health.Add("Псориаз (тяжелая степень)");
            specifications.Health.Add("СПИД");
            specifications.Health.Add("Бронхит (легкое течение)");
            specifications.Health.Add("Бронхит (среднея степень)");
            specifications.Health.Add("Бронхит (тяжелое течение)");
            specifications.Health.Add("Дальтонизм (для тебя мир черно-белый)");
            specifications.Health.Add("Алкоголизм (легкая степень)"); 
            specifications.Health.Add("Алкоголизм (среднея степень)");
            specifications.Health.Add("Алкоголизм (тяжелая степень)");
            specifications.Health.Add("Коронавирус (легкое течение)");
            specifications.Health.Add("Коронавирус (среднея степень)");
            specifications.Health.Add("Коронавирус (тяжелое течение)");
            specifications.Health.Add("Диарея (легкое течение)");
            specifications.Health.Add("Диарея (среднея степень)");
            specifications.Health.Add("Диарея (тяжелое течение)");
            specifications.Health.Add("Диарея (степень - ад)");
            specifications.Health.Add("Порок сердца (легкая степень)"); 
            specifications.Health.Add("Порок сердца (среднея степень)");
            specifications.Health.Add("Порок сердца (тяжелая степень)");
            specifications.Health.Add("Альбинизм");
            specifications.Health.Add("Слепота (легкая степень)"); 
            specifications.Health.Add("Слепота (среднея степень)");
            specifications.Health.Add("Слепота (тяжелая степень)");
        }
    }
}
