using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Bunker.Models.Init_Models
{
    class Init_Phobia
    {
        private Specifications specifications;
        public Init_Phobia(Specifications _specifications)
        {
            specifications = _specifications;
            Fill_Phobia();
        }

        private void Fill_Phobia()
        {
            specifications.Phobia.Add("аблютофобия(аблутофобия) — боязнь умывания, купания, стирки или чистки");
            specifications.Phobia.Add("авиафобия, авиофобия — боязнь полётов в воздушных транспортных средствах");
            specifications.Phobia.Add("агирофобия(дромофобия) — боязнь улиц, пересекать улицу");
            specifications.Phobia.Add("агорафобия — боязнь пространства, открытых мест, площадей, толп людей, рынков");
            specifications.Phobia.Add("аграфобия(контрелтофобия) — боязнь сексуальных домогательств, секса");
            specifications.Phobia.Add("айлурофобия(галеофобия, гатофобия, фелинофобия) — боязнь кошек");
            specifications.Phobia.Add("айхмофобия — боязнь острых предметов");
            specifications.Phobia.Add("акарофобия — боязнь клещей");
            specifications.Phobia.Add("аквафобия — боязнь воды, утопления");
            specifications.Phobia.Add("аккультурафобия — боязнь ассимиляции");
            specifications.Phobia.Add("аклиофобия — боязнь глухоты");
            specifications.Phobia.Add("акнефобия — боязнь появления угрей(акне)");
            specifications.Phobia.Add("акротомофобия — боязнь ампутации");
            specifications.Phobia.Add("акрофобия — боязнь высоты");
            specifications.Phobia.Add("акусапунгерефобия — боязнь акупунктуры");
            specifications.Phobia.Add("акустикофобия(лигирофобия, фонофобия) — боязнь громких звуков");
            specifications.Phobia.Add("алгофобия — боязнь боли");
            specifications.Phobia.Add("амаксофобия — боязнь транспорта и вождения");
            specifications.Phobia.Add("аматофобия — боязнь пыли или загрязнения пылью");
            specifications.Phobia.Add("ангинофобия — боязнь приступа стенокардии");
            specifications.Phobia.Add("андрофобия — боязнь мужчин");
            specifications.Phobia.Add("анемофобия — боязнь бури(сильного ветра)");
            specifications.Phobia.Add("антофобия — боязнь цветов");
            specifications.Phobia.Add("антропофобия — боязнь людей или компании людей, форма социальной фобии");
            specifications.Phobia.Add("апейрофобия — боязнь бесконечности");
            specifications.Phobia.Add("апифобия — боязнь пчёл, ос); частный случай зоофобии");
            specifications.Phobia.Add("апопатофобия — боязнь заходить в туалеты");
            specifications.Phobia.Add("апоплексифобия — боязнь возникновения инсульта");
            specifications.Phobia.Add("арахнофобия — боязнь пауков); частный случай зоофобии");
            specifications.Phobia.Add("аритмофобия, арифмофобия — боязнь перед каким - либо индивидуально значимым числом");
            specifications.Phobia.Add("астрофобия — боязнь звёзд и звёздного пространства");
            specifications.Phobia.Add("атаксиофобия — боязнь нарушения координации движений");
            specifications.Phobia.Add("атихифобия — боязнь совершить ошибку, потерпеть неудачу");
            specifications.Phobia.Add("аурофобия — боязнь золота");
            specifications.Phobia.Add("аутомизофобия — боязнь загрязнить своё тело");
            specifications.Phobia.Add("аутофобия(ануптафобия, эремофобия, изолофобия) — боязнь одиночества");
            specifications.Phobia.Add("афефобия — см.гаптофобия");
            specifications.Phobia.Add("ахлуофобия — боязнь темноты, см. никтофобия");
            specifications.Phobia.Add("ацерофобия — боязнь кислых продуктов и напитков");
            specifications.Phobia.Add("аэрофобия — боязнь полётов на летательных аппаратах); также боязнь сквозняков");
            specifications.Phobia.Add("аэроэмфиземофобия — боязнь кессонной болезни");
            specifications.Phobia.Add("базофобия — боязнь ходьбы");
            specifications.Phobia.Add("бактериофобия(бациллофобия) — боязнь заразиться бактериями");
            specifications.Phobia.Add("баллистофобия — боязнь поражения пулей, бомбой или снарядом");
            specifications.Phobia.Add("барофобия — боязнь подъёма тяжести");
            specifications.Phobia.Add("батеофобия — см.акрофобия");
            specifications.Phobia.Add("белонофобия — см.айхмофобия");
            specifications.Phobia.Add("блаптофобия — боязнь нанести кому - либо повреждение");
            specifications.Phobia.Add("бромгидрофобия");
            specifications.Phobia.Add("(бромидрозифобия, бромидрофобия) — боязнь, что окружающие могут заметить неприятный запах тела или потливость больного данной фобий");
            specifications.Phobia.Add("бронтофобия — боязнь грома");
            specifications.Phobia.Add("вакцинофобия — боязнь прививок и связанных с ними неврологических осложнений");
            specifications.Phobia.Add("венерофобия(кипридофобия) — боязнь заразиться венерической болезнью");
            specifications.Phobia.Add("вербофобия — страх отдельных слов");
            specifications.Phobia.Add("верминофобия — боязнь бактерий, микробов, червей, заразиться");
            specifications.Phobia.Add("вертигофобия(динофобия) — боязнь головокружения");
            specifications.Phobia.Add("винофобия — боязнь употребления вина");
            specifications.Phobia.Add("вомитофобия — см.эметофобия");
            specifications.Phobia.Add("галеофобия — боязнь акул");
            specifications.Phobia.Add("галитофобия — боязнь неприятного запаха изо рта");
            specifications.Phobia.Add("гамофобия — боязнь вступления в брак");
            specifications.Phobia.Add("гаптофобия(афефобия, гафефобия, гафофобия, гапнофобия, гаптефобия, тиксофобия) — боязнь прикосновения окружающих людей");
            specifications.Phobia.Add("гарпаксофобия — см.харпаксофобия");
            specifications.Phobia.Add("гедонофобия — боязнь удовольствия, наслаждения");
            specifications.Phobia.Add("гексакосиойгексеконтагексафобия — страх числа 666");
            specifications.Phobia.Add("гелиофобия(гелеофобия) — боязнь солнца, солнечного света, страх пребывания на солнце");
            specifications.Phobia.Add("гелотофобия — страх оказаться объектом юмора, насмешек");
            specifications.Phobia.Add("гемофобия(гематофобия, гемафобия) — боязнь крови");
            specifications.Phobia.Add("генофобия, коитофобия, коитуфобия, миксеофобия, миксофобия — страх секса, сексуальных контактов");
            specifications.Phobia.Add("геронтофобия(гераскофобия) — страх общения с пожилыми людьми или собственного старения");
            specifications.Phobia.Add("гермофобия — см.мизофобия");
            specifications.Phobia.Add("герпетофобия — боязнь рептилий, пресмыкающихся, змей); частный случай зоофобии");
            specifications.Phobia.Add("гетерофобия — боязнь противоположного пола");
            specifications.Phobia.Add("гефирофобия — боязнь мостов");
            specifications.Phobia.Add("гидрозофобия — боязнь вспотеть");
            specifications.Phobia.Add("гидрофобия(аквафобия) — боязнь воды, сырости, жидкостей");
            specifications.Phobia.Add("гиерофобия — боязнь предметов религиозного культа");
            specifications.Phobia.Add("гилофобия(ксилофобия, никтогилофобия, хилофобия) — боязнь леса, заблудиться в лесу");
            specifications.Phobia.Add("гимнофобия — боязнь наготы");
            specifications.Phobia.Add("гинекофобия(гинефобия, гинофобия) — боязнь женщин");
            specifications.Phobia.Add("гипенгиофобия(хипенгиофобия) — боязнь взять на себя ответственность");
            specifications.Phobia.Add("гипнофобия — боязнь заснуть");
            specifications.Phobia.Add("глоссофобия — см.логофобия");
            specifications.Phobia.Add("гнозиофобия(эпистемофобия) — боязнь знания/ познания");
            specifications.Phobia.Add("гомофобия(гомофобия) — боязнь любого проявления гомосексуальности");
            specifications.Phobia.Add("гравидофобия — боязнь встречи с беременной, беременности");
            specifications.Phobia.Add("графофобия — боязнь писа́ть или брать в руки письменные принадлежности");
            specifications.Phobia.Add("декстрофобия — боязнь вещей, расположенных справа");
            specifications.Phobia.Add("демонофобия(cатанофобия) — боязнь Дьявола, демонов и другой нечистой силы");
            specifications.Phobia.Add("демофобия(охлофобия) — боязнь скопления людей, толпы");
            specifications.Phobia.Add("дентофобия(одонтофобия) — боязнь стоматологов, лечения зубов");
            specifications.Phobia.Add("дерматопатофобия(дерматофобия, дерматосиофобия) — боязнь заболеть кожной болезнью");
            specifications.Phobia.Add("децидофобия — боязнь принимать решения");
            specifications.Phobia.Add("динофобия — см.вертигофобия");
            specifications.Phobia.Add("дисморфофобия — боязнь физических недостатков в собственной внешности");
            specifications.Phobia.Add("дорофобия — боязнь получать или делать подарки");
            specifications.Phobia.Add("дромофобия — см.агирофобия");
            specifications.Phobia.Add("зоофобия — боязнь животных");
            specifications.Phobia.Add("земмифобия — боязнь кротов");
            specifications.Phobia.Add("иатрофобия — см.ятрофобия");
            specifications.Phobia.Add("инсектофобия(энтомофобия) — боязнь насекомых); частный случай зоофобии");
            specifications.Phobia.Add("иерофобия — боязнь предметов религиозного культа); см.также агиофобия");
            specifications.Phobia.Add("иофобия — боязнь ядов");
            specifications.Phobia.Add("какоррафиофобия — см.атихифобия");
            specifications.Phobia.Add("калифобия — боязнь красоты");
            specifications.Phobia.Add("канцерофобия(канкрофобия, карциномофобия, карцинофобия, кацерофобия) — боязнь заболеть раком, злокачественной опухолью");
            specifications.Phobia.Add("кардиопатофобия(кардиофобия) — боязнь сердечного заболевания");
            specifications.Phobia.Add("катагелофобия — боязнь насмешки");
            specifications.Phobia.Add("кейрофобия — боязнь при бритье порезать клиента(у парикмахеров)");
            specifications.Phobia.Add("кенофобия — боязнь больших незаполненных пространств(например, пустого зала театра)");
            specifications.Phobia.Add("кераунофобия — боязнь молний");
            specifications.Phobia.Add("кинофобия(канинофобия) — боязнь собак");
            specifications.Phobia.Add("кипридофобия — см.венерофобия");
            specifications.Phobia.Add("клаустрофобия — боязнь замкнутого пространства");
            specifications.Phobia.Add("клептофобия — боязнь украсть, либо страх быть обокраденным");
            specifications.Phobia.Add("климакофобия(климактофобия) — боязнь ходьбы по лестнице, лестниц");
            specifications.Phobia.Add("коинофобия — боязнь заходить в помещение, где находится много людей");
            specifications.Phobia.Add("коитофобия — см.генофобия");
            specifications.Phobia.Add("компьютерофобия — боязнь компьютеров");
            specifications.Phobia.Add("контрелтофобия — см.аграфобия");
            specifications.Phobia.Add("копофобия — боязнь переутомиться");
            specifications.Phobia.Add("копрофобия — боязнь фекалий");
            specifications.Phobia.Add("коулрофобия — боязнь клоунов");
            specifications.Phobia.Add("ксенофобия — страх или ненависть к кому - либо или чему-либо чужому, незнакомому, непривычному");
            specifications.Phobia.Add("кремнофобия — боязнь смотреть в бездну, пропасть");
            specifications.Phobia.Add("кристаллофобия — боязнь прикосновения к стеклянным предметам");
            specifications.Phobia.Add("ксилофобия — см.гилофобия");
            specifications.Phobia.Add("кумпунофобия — боязнь пуговиц");
            specifications.Phobia.Add("лалофобия — боязнь говорить из - за опасения возможного заикания");
            specifications.Phobia.Add("латерофобия — боязнь лежать на боку, чаще — на левом(когда присутствует кардиофобия)");
            specifications.Phobia.Add("лепрофобия — боязнь заразиться лепрой");
            specifications.Phobia.Add("лигирофобия — см.акустикофобия");
            specifications.Phobia.Add("лисофобия — боязнь заболеть бешенством");
            specifications.Phobia.Add("лифтофобия — боязнь лифтов");
            specifications.Phobia.Add("логофобия(глоссофобия) — страх говорить");
            specifications.Phobia.Add("люофобия(сифилофобия) — боязнь заразиться сифилисом");
            specifications.Phobia.Add("маниофобия — боязнь психически заболеть");
            specifications.Phobia.Add("мегалофобия — боязнь больших предметов или объектов");
            specifications.Phobia.Add("менофобия — боязнь менструаций и связанных с ними неприятных ощущений");
            specifications.Phobia.Add("металлофобия — боязнь металлических предметов и металлов");
            specifications.Phobia.Add("мизофобия(гермофобия) — боязнь заразиться инфекционным заболеванием, грязи, прикосновения к окружающим предметам");
            specifications.Phobia.Add("миксеофобия — см.генофобия");
            specifications.Phobia.Add("мирмекофобия — боязнь муравьёв); частный случай зоофобии");
            specifications.Phobia.Add("морфинофобия — боязнь стать морфинистом");
            specifications.Phobia.Add("мусофобия(сурифобия) — боязнь мышей и крыс");
            specifications.Phobia.Add("некрофобия — боязнь трупов и похоронных принадлежностей");
            specifications.Phobia.Add("неофобия (англ.) — боязнь нового, перемен");
            specifications.Phobia.Add("никтогилофобия — см. гилофобия");
            specifications.Phobia.Add("никтофобия (ахлуофобия, скотофобия, эклуофобия) — боязнь темноты, ночи");
            specifications.Phobia.Add("номофобия — боязнь остаться без мобильного телефона, без связи");
            specifications.Phobia.Add("нозофобия — боязнь заболеть");
            specifications.Phobia.Add("нозокомефобия (англ.) — боязнь больниц");
            specifications.Phobia.Add("одонтофобия — см. дентофобия");
            specifications.Phobia.Add("ойкофобия — боязнь дома, возвращения домой");
            specifications.Phobia.Add("омброфобия — боязнь попасть под дождь");
            specifications.Phobia.Add("онанофобия — боязнь вредных последствий онанизма");
            specifications.Phobia.Add("осмофобия (англ.) — боязнь телесных запахов");
            specifications.Phobia.Add("орнитофобия — боязнь птиц); частный случай зоофобии");
            specifications.Phobia.Add("офидиофобия (англ.), или офиофобия — боязнь змей); частный случай герпетофобии");
            specifications.Phobia.Add("охлофобия — боязнь толпы, см. демофобия");
            specifications.Phobia.Add("панофобия (панфобия, пантофобия) — боязнь всего или постоянный страх по неизвестной причине");
            specifications.Phobia.Add("паразитофобия — боязнь насекомых-паразитов");
            specifications.Phobia.Add("паралипофобия — боязнь, что собственные ошибочные действия причинят вред близким родственникам");
            specifications.Phobia.Add("параскаведекатриафобия — боязнь пятницы, 13-го дня месяца");
            specifications.Phobia.Add("патройофобия — боязнь наследственности, в особенности наследственных заболеваний");
            specifications.Phobia.Add("парурез — боязнь мочеиспускания на людях");
            specifications.Phobia.Add("педиофобия — боязнь предметов, имитирующих человеческий облик (кукол, восковых фигур)");
            specifications.Phobia.Add("педофобия — навязчивый страх детей или имитирующих их изделий (кукол)");
            specifications.Phobia.Add("пейрафобия — боязнь публичного выступления");
            specifications.Phobia.Add("пеладофобия — боязнь облысения");
            specifications.Phobia.Add("петтофобия — боязнь неудержания газов в присутствии посторонних людей");
            specifications.Phobia.Add("пирофобия — боязнь огня, пожаров, гибели от огня");
            specifications.Phobia.Add("психрофобия — боязнь холода");
            specifications.Phobia.Add("рабдофобия — боязнь наказания");
            specifications.Phobia.Add("радиофобия — боязнь радиации");
            specifications.Phobia.Add("ранидофобия — боязнь лягушек");
            specifications.Phobia.Add("ректофобия — боязнь не иметь стула");
            specifications.Phobia.Add("рипофобия — боязнь грязи, нечистот");
            specifications.Phobia.Add("робофобия — страх по отношению к любой робототехнике");
            specifications.Phobia.Add("cатанофобия — см. демонофобия");
            specifications.Phobia.Add("селахофобия — боязнь акул");
            specifications.Phobia.Add("сидеродромофобия — боязнь езды в железнодорожном транспорте");
            specifications.Phobia.Add("ситофобия — боязнь приёма пищи");
            specifications.Phobia.Add("скабиофобия — боязнь заболеть чесоткой");
            specifications.Phobia.Add("сколецифобия — боязнь червей, заразных насекомых); частный случай зоофобии");
            specifications.Phobia.Add("скопофобия (англ.) (скоптофобия) — боязнь пристального разглядывания другими");
            specifications.Phobia.Add("скотофобия — см. никтофобия");
            specifications.Phobia.Add("сомнифобия — боязнь спать");
            specifications.Phobia.Add("социофобия — боязнь общества, контактов, неловкого поведения в обществе, оценки окружающими");
            specifications.Phobia.Add("спектрофобия?! — 1) боязнь призраков");
            specifications.Phobia.Add("спектрофобия — 2) то же, что эйсоптрофобия");
            specifications.Phobia.Add("спермофобия — боязнь микробов");
            specifications.Phobia.Add("спидофобия — боязнь заразиться СПИДом");
            specifications.Phobia.Add("cтазобазофобия — боязнь стояния и ходьбы");
            specifications.Phobia.Add("сурифобия — см. мусофобия");
            specifications.Phobia.Add("табофобия — боязнь заболеть спинной сухоткой");
            specifications.Phobia.Add("талассофобия — боязнь моря (в том числе купания и морских путешествий)");
            specifications.Phobia.Add("танатофобия — боязнь смерти");
            specifications.Phobia.Add("тафофобия (тафефобия) — боязнь быть погребенным заживо, похорон");
            specifications.Phobia.Add("телефонофобия — боязнь телефона, ожидания телефонного звонка");
            specifications.Phobia.Add("терророфобия — боязнь терроризма");
            specifications.Phobia.Add("тениофобия — боязнь заразиться глистами");
            specifications.Phobia.Add("теофобия — боязнь бога, его вмешательства в судьбу или кары");
            specifications.Phobia.Add("термофобия — боязнь жары и натопленных помещений");
            specifications.Phobia.Add("тетрафобия — боязнь числа 4");
            specifications.Phobia.Add("тиксофобия — см. гаптофобия");
            specifications.Phobia.Add("токофобия (малевзиофобия) — страх перед родами");
            specifications.Phobia.Add("токсикофобия — боязнь отравления");
            specifications.Phobia.Add("топофобия — боязнь остаться одному в помещении");
            specifications.Phobia.Add("травматофобия (англ.) — боязнь травмы");
            specifications.Phobia.Add("трансфобия — боязнь и, как следствие, неприятие и негативная реакция на проявления трансгендерности");
            specifications.Phobia.Add("тремофобия — боязнь дрожания");
            specifications.Phobia.Add("трипанофобия — боязнь игл и уколов");
            specifications.Phobia.Add("трипофобия — страх перед кластерными отверстиями (не признана в Диагностической Американской Психиатрической Ассоциации).");
            specifications.Phobia.Add("трискаидекафобия (трискайдекафобия, тредекафобия, тердекафобия) — боязнь числа 13");
            specifications.Phobia.Add("трихофобия (англ.) — боязнь попадания волос в пищу, на одежду, на поверхность тела");
            specifications.Phobia.Add("туберкулёзофобия (фтизиофобия) — боязнь заболеть туберкулёзом");
            specifications.Phobia.Add("туннелефобия — боязнь прохождения через туннель");
            specifications.Phobia.Add("уранофобия — боязнь смотреть в небо");
            specifications.Phobia.Add("фагофобия — боязнь глотания, подавиться пищей");
            specifications.Phobia.Add("фазмофобия — боязнь призраков и духов");
            specifications.Phobia.Add("фармакофобия — боязнь принимать лекарства");
            specifications.Phobia.Add("филофобия — боязнь влюбиться");
            specifications.Phobia.Add("фобофобия (фобиофобия) — боязнь фобий (страхов), появления симптомов страха, боязнь испытать испуг");
            specifications.Phobia.Add("фонофобия — см. акустикофобия");
            specifications.Phobia.Add("фтириофобия — боязнь вшивости.");
            specifications.Phobia.Add("фриггатрискаидекафобия — см. параскаведекатриафобия");
            specifications.Phobia.Add("хайрофобия — боязнь появления чувства веселья в неподобающей обстановке");
            specifications.Phobia.Add("харпаксофобия (гарпаксофобия) — боязнь разбойников, быть ограбленным");
            specifications.Phobia.Add("хемофобия — боязнь химии");
            specifications.Phobia.Add("хилофобия — см. гилофобия");
            specifications.Phobia.Add("хироптофобия — боязнь летучих мышей); частный случай зоофобии");
            specifications.Phobia.Add("хоплофобия (гоплофобия) — боязнь оружия");
            specifications.Phobia.Add("хрематофобия — боязнь прикосновения к деньгам");
            specifications.Phobia.Add("хроматофобия (хромофобия) — боязнь какого-либо цвета и окрашенных в него предметов");
            specifications.Phobia.Add("хронофобия — боязнь времени");
            specifications.Phobia.Add("эйсоптрофобия (спектрофобия) — боязнь собственного отражения в зеркале");
            specifications.Phobia.Add("эйхофобия — боязнь произносить или выслушивать добрые пожелания");
            specifications.Phobia.Add("эквинофобия (англ.) (гиппофобия) — боязнь лошадей); частный случай зоофобии");
            specifications.Phobia.Add("эклуофобия — см. никтофобия");
            specifications.Phobia.Add("эметофобия (вомитофобия) — боязнь появления рвоты");
            specifications.Phobia.Add("эпистаксофобия (эпистаксиофобия) — боязнь носового кровотечения");
            specifications.Phobia.Add("эргазиофобия (англ.) — боязнь оперировать (у врачей-хирургов)");
            specifications.Phobia.Add("эргофобия — боязнь работать, совершать какие-либо действия");
            specifications.Phobia.Add("эритрофобия (англ.) (эрейтофобия) — боязнь покраснения лица (боязнь покраснеть на людях)");
            specifications.Phobia.Add("эротофобия — боязнь секса или вопросов о сексе");
            specifications.Phobia.Add("эфебифобия — боязнь подростков");
            specifications.Phobia.Add("ятрофобия — боязнь врачей");
        }


    }
}
