using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Bunker.Models.Init_Models
{
    class Init_Info
    {
        private Specifications specifications;
        public Init_Info(Specifications _specifications)
        {
            specifications = _specifications;
            Fill_Info();
        }

        private void Fill_Info()
        {
            specifications.Add_Info.Add("Владеет языком жестов");
            specifications.Add_Info.Add("Воровал деньги у собственных родителей на развлечения");
            specifications.Add_Info.Add("Имеет образование химика");
            specifications.Add_Info.Add("В душе архитектор");
            specifications.Add_Info.Add("Знает структуру компьютеров");
            specifications.Add_Info.Add("Совершил кругосветное путешествие");
            specifications.Add_Info.Add("Верит в духов, Имеет образование биолога");
            specifications.Add_Info.Add("Разговаривает с духами");
            specifications.Add_Info.Add("Осилил книги 'Война и мир' дважды");
            specifications.Add_Info.Add("Родители занимались скотоводством");
            specifications.Add_Info.Add("Состоял в преступной группировке");
            specifications.Add_Info.Add("Лишил жизни человека");
            specifications.Add_Info.Add("Разбирается в людях");
            specifications.Add_Info.Add("Знает серьезных дяденек");
            specifications.Add_Info.Add("Изучил сложные химические процессы и технологию производства алкоголя");
            specifications.Add_Info.Add("Хорошая физическая подготовка");
            specifications.Add_Info.Add("Родители занимались фермерством");
            specifications.Add_Info.Add("Лоликонщик");
            specifications.Add_Info.Add("Ориентируется по звёздам");
            specifications.Add_Info.Add("Пересмотрел кучу передач про выживание");
            specifications.Add_Info.Add("Помешан на зомби");
            specifications.Add_Info.Add("Умеет манипулировать людьми");
            specifications.Add_Info.Add("В детстве мечтал стать космонавтом");
            specifications.Add_Info.Add("Увлекается нумерологией");
            specifications.Add_Info.Add("Любит спать днём");
            specifications.Add_Info.Add("Учился готовить с детства");
            specifications.Add_Info.Add("Умеет забивать кальяны");
            specifications.Add_Info.Add("Понимает животных");
            specifications.Add_Info.Add("Умеет стрелять из лука");
            specifications.Add_Info.Add("Лично знаком с Президентом");
            specifications.Add_Info.Add("Присутствовал на раскопках");
            specifications.Add_Info.Add("Может пойти кровь из носа");
            specifications.Add_Info.Add("Любит обрабатывать грядки");
            specifications.Add_Info.Add("Умеет выращивать огурцы");
            specifications.Add_Info.Add("Потомственный алхимик");
            specifications.Add_Info.Add("Купил муравьиную ферму");
            specifications.Add_Info.Add("Отдыхал в Африке");
            specifications.Add_Info.Add("Умеет обрабатывать деревья");
            specifications.Add_Info.Add("В классе был отличником");
            specifications.Add_Info.Add("Дегустатор алкоголя");
            specifications.Add_Info.Add("Имеет иммунитет к ядам");
            specifications.Add_Info.Add("Профессиональный вор");
            specifications.Add_Info.Add("Умеет ориентироваться на местности");
            specifications.Add_Info.Add("Пересмотрел все трендовые аниме");
            specifications.Add_Info.Add("Писает выше своей головы");
            specifications.Add_Info.Add("Плюёт на 3 метра");
            specifications.Add_Info.Add("Выиграл лотерею");
            specifications.Add_Info.Add("Обладает языком змей");
            specifications.Add_Info.Add("Знает наизусть все сцены из сумерек");
            specifications.Add_Info.Add("Продал почку");
            specifications.Add_Info.Add("Проектировал этот бункер");
            specifications.Add_Info.Add("Проходил курсы сексолога");
            specifications.Add_Info.Add("Резидент Камеди Клаб");
            specifications.Add_Info.Add("Думает, что он улитка");
            specifications.Add_Info.Add("Любит ловить бабочек");
            specifications.Add_Info.Add("Может отличить манго от маракуйи");
            specifications.Add_Info.Add("Проектировал соседний бункер");
            specifications.Add_Info.Add("Пережил несколько вспышек короновируса");
            specifications.Add_Info.Add("Съел ту самую летучую мышь");
            specifications.Add_Info.Add("Хорошо видит в темноте");
            specifications.Add_Info.Add("Чемпион игр в прятки");
            specifications.Add_Info.Add("Занимаю деньги у друзей не рассчитывая вернуть долги");
            specifications.Add_Info.Add("Если есть какой-то план, я его наверняка забуду. А если не забуду, то попросту проигнорирую");
            specifications.Add_Info.Add("Мою семью по ошибке посадили в тюрьму");
            specifications.Add_Info.Add("Я хочу отомстить за племя которое было уничтожено");
            specifications.Add_Info.Add("Я украл личность и должность другого человека чтобы поступить в академию");
            specifications.Add_Info.Add("Я выжил лишь благодаря другому беспризорнику, что передал мне знания, как вести себя на улицах");
            specifications.Add_Info.Add("Я глубоко суеверен и у меня есть много ритуалов, чтобы избежать неудачи");
            specifications.Add_Info.Add("Выросши в богатстве, я небрежен с финансами");
            specifications.Add_Info.Add("Я сражаюсь за тех, кто не может это сделать сам");
            specifications.Add_Info.Add("Ваше воспитание в трущобах научило вас важным вещам о выживании ценой элементарных вещей, известных другим. К сожалению, среди них оказалась и личная гигиена.");
            specifications.Add_Info.Add("Я не могу скрывать свои истинные чувства. Острый язык всегда приносит мне неприятности");
            specifications.Add_Info.Add("Я пойду на всё ради славы и известности");
            specifications.Add_Info.Add("Свои заработанные деньги я трачу на помощь своей семье");
            specifications.Add_Info.Add("Мой помощник везде сопровождает меня");
            specifications.Add_Info.Add("Мой напарник погиб из-за ошибки, которую я совершил. Это не повториться вновь");
            specifications.Add_Info.Add("Я жду того дня, когда верну свой дом");
            specifications.Add_Info.Add("Я получил шанс начать новую жизнь, и собираюсь сделать все правильно");
            specifications.Add_Info.Add("Как бы усердно я не учился, или сколь многого бы я не добивался, моей семье всегда этого будет мало");
            specifications.Add_Info.Add("Ярость к врагам ослепляет меня и делает безрассудным");
            specifications.Add_Info.Add("Я люблю пировать на останках врагов.");
            specifications.Add_Info.Add("Я прикидываюсь, что не понимаю местного языка, для того чтобы избежать взаимодействий, которые мне не по нраву");
            specifications.Add_Info.Add("В моем прошлом есть травма, которая всюду сопровождает меня");
            specifications.Add_Info.Add("Я верю, что мой интеллект намного выше, чем у тех народов, которые я изучаю. Я уверен, что смогу многому их научить");
            specifications.Add_Info.Add("Я одержим теориями заговора и беспокоюсь о тайных обществах и скрытых демонах");
            specifications.Add_Info.Add("С раннего детства я слушал рассказы о затерянном городе. Я найду его, разгадаю его секреты и займу свое место в анналах истории");
            specifications.Add_Info.Add("Мне всегда кажется, что меня пытаются обжулить");
            specifications.Add_Info.Add("Я выгляжу умопомрачительно");
            specifications.Add_Info.Add("Мне некомфортно под открытым небом. Я стараюсь проводить время в помещении или под землей");
            specifications.Add_Info.Add("Я должен быть капитаном любой группы, к которой присоединяюсь");
            specifications.Add_Info.Add("Я недооцениваю и смотрю сверху вниз на простых людей");
            specifications.Add_Info.Add("Я хочу быть знаменитым, чего бы это ни стоило");
            specifications.Add_Info.Add("Я боготворю героя старых рассказов, и всегда сравниваю свои поступки с его");
            specifications.Add_Info.Add("Не могу устоять перед смазливым личиком");
            specifications.Add_Info.Add("У меня есть саморазрушительный порок, которому я в тайне потворствую");
            specifications.Add_Info.Add("Я резко реагирую на некоторые действия и мотивы местных людей, потому что эти люди отличаются от меня");
            specifications.Add_Info.Add("У меня нет времени на друзей или семью. Каждую свободную минуту я трачу на подготовку или обдумывание своей следующей экспедиции");
            specifications.Add_Info.Add("Я не привык быть рядом с людьми, и часто брюзжу из-за этого");
            specifications.Add_Info.Add("Я не способен следовать планам");
            specifications.Add_Info.Add("Когда есть выбор, идти направо или налево, я всегда выбираю налево");
            specifications.Add_Info.Add("Мое желание мести часто навлекает на меня проблемы");
            specifications.Add_Info.Add("Моё любопытство подавляет мой страх. Однажды это меня убьёт");
            specifications.Add_Info.Add("Я боюсь мысли о становлении полностью неживым и готов пойти на что угодно, чтобы этого не случилось");
            specifications.Add_Info.Add("Я скрываю позорную тайну, которая может уничтожить мою семью");
            specifications.Add_Info.Add("Я не могу вернуться домой из-за скандала. Неприятности такого рода словно преследуют меня");
            specifications.Add_Info.Add("Я в тайне боюсь одного из обычных диких животных");
            specifications.Add_Info.Add("Моя ошибка причинила боль кому-то. Я больше никогда не совершу эту ошибку");
            specifications.Add_Info.Add("Однажды я высмеял дворянина, который всё ещё хочет оторвать мне голову. Это была ошибка, но я могу повторить её ещё неоднократно");
            specifications.Add_Info.Add("Я с пренебрежением отношусь к любому, кто не владеет луком");
            specifications.Add_Info.Add("Я быстро отсеиваю мнения других");
            specifications.Add_Info.Add("У меня есть привычка, которая выдаёт меня, когда я вру");
            specifications.Add_Info.Add("Я пытаюсь отменить все плохие вещи, которые натворил за жизнь");
            specifications.Add_Info.Add("Невинный человек находится в тюрьме из-за меня");
            specifications.Add_Info.Add("Я в неоплатном долгу перед человеком, что сжалился и помог мне");
            specifications.Add_Info.Add("Я виновен в ужасающем преступлении. Надеюсь, я смогу простить себя за это");
            specifications.Add_Info.Add("Я ношу характерный предмет гардероба, стиль усов или аксессуар");
            specifications.Add_Info.Add("Я считаю последователей других богов по меньшей мере заблудшими овцами, или невежественными дураками по большей мере");
            specifications.Add_Info.Add("Во время обучения, я нарушил одно из эзотерических правил, которое тогда казалось безвредным. Если кто-то узнает, мне придётся очень дорого заплатить");
            specifications.Add_Info.Add("Я спонсирую приют, чтобы оградить других от того, что пришлось пережить мне");
            specifications.Add_Info.Add("Я одержим желанием разбогатеть, у меня всегда есть схема, как отлично навариться");
            specifications.Add_Info.Add("Я не могу уйти из комнаты, не попытавшись найти потайную дверь");
            specifications.Add_Info.Add("Я втайне считаю всех ниже себя");
            specifications.Add_Info.Add("У меня затяжная боль из-за старых травм");
            specifications.Add_Info.Add("Кое-кто спас мне жизнь на улицах. С тех пор я никогда не оставляю друзей, оставшихся в беде");
            specifications.Add_Info.Add("Я не буду продавать предмет искусства или другое сокровище, если оно имеет культурную ценность");
            specifications.Add_Info.Add("Все детство провел на улице");
            specifications.Add_Info.Add("Имеет медицинское образование");
            specifications.Add_Info.Add("Изучил сложные химические процессы и технологию производства алкоголя");
            specifications.Add_Info.Add("Мастер спорта по борьбе");
            specifications.Add_Info.Add("Имеет образование химика");
            specifications.Add_Info.Add("Обманывал в детстве других детей");
            specifications.Add_Info.Add("Ориентируется по звездам");
            specifications.Add_Info.Add("Любит кулинарию и необычайно вкусно готовит");
            specifications.Add_Info.Add("Пару раз читал 'Метро' Глуховского");
            specifications.Add_Info.Add("Помешанный на зомби");
            specifications.Add_Info.Add("В детстве была мечта стать космонавтом");
            specifications.Add_Info.Add("Изучал составы различных жидкостей");
            specifications.Add_Info.Add("Знает структуру компьютеров");
            specifications.Add_Info.Add("Родители занимались скотоводством");
            specifications.Add_Info.Add("Обьездил всю планету");
            specifications.Add_Info.Add("Лишил жизни человека");
            specifications.Add_Info.Add("Умеет манипулировать людьми");
            specifications.Add_Info.Add("Воспитывался в строгой военной дисциплине");
            specifications.Add_Info.Add("Владеет языком жестов");
            specifications.Add_Info.Add("Верит в заговоры");
            specifications.Add_Info.Add("Умеет вскрывать замки");
            specifications.Add_Info.Add("Разбирается в людях");
            specifications.Add_Info.Add("Знает множество стихотворений");
            specifications.Add_Info.Add("Выиграл в лотерею");
            specifications.Add_Info.Add("Знает несколько языков");
            specifications.Add_Info.Add("Родители занимались фермерством");
            specifications.Add_Info.Add("Приходилось принимать роды");
            specifications.Add_Info.Add("Преуспевал в учебе и был умнее сверстников");
            specifications.Add_Info.Add("Обманывал в детстве других детей");
            specifications.Add_Info.Add("Знает азбуку морзе");
            specifications.Add_Info.Add("В душе архитектор");
            specifications.Add_Info.Add("Проходил курсы психолога");
            specifications.Add_Info.Add("Верит в духов");
            specifications.Add_Info.Add("Хорошая физическая подготовка");
            specifications.Add_Info.Add("Имеет образование биолога");
            specifications.Add_Info.Add("Любит горячую выпечку");
            specifications.Add_Info.Add("Воровал деньги у собственных родителей на развлечения");
        }
    }
}
