using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Bunker.Models.Init_Models
{
    class Init_Luggage
    {
        private Specifications specifications;
        public Init_Luggage(Specifications _specifications)
        {
            specifications = _specifications;

            Fill_Luggage();
        }

        private void Fill_Luggage()
        {
            specifications.Luggage.Add("Икона Святой Богородицы");
            specifications.Luggage.Add("Горшочный цветок");
            specifications.Luggage.Add("Арбуз");
            specifications.Luggage.Add("Карта мира");
            specifications.Luggage.Add("Кальян");
            specifications.Luggage.Add("Колчан и 10 стрел");
            specifications.Luggage.Add("Домино");
            specifications.Luggage.Add("Презервативы");
            specifications.Luggage.Add("Домашний инкубатор");
            specifications.Luggage.Add("Коробка алкоголя");
            specifications.Luggage.Add("Маска и трубка для плавания");
            specifications.Luggage.Add("Живая утка");
            specifications.Luggage.Add("Сумка ветеринара");
            specifications.Luggage.Add("Куриный бульон");
            specifications.Luggage.Add("Самогонный аппарат");
            specifications.Luggage.Add("Упаковка растворимого кофе");
            specifications.Luggage.Add("Кошка");
            specifications.Luggage.Add("Собака");
            specifications.Luggage.Add("Прирученный крокодил");
            specifications.Luggage.Add("Сумка с таблетками");
            specifications.Luggage.Add("Ювелирные украшения");
            specifications.Luggage.Add("Пакет насвая");
            specifications.Luggage.Add("Вентилятор");
            specifications.Luggage.Add("Робот на радиоуправление");
            specifications.Luggage.Add("Пакет с чаем");
            specifications.Luggage.Add("Все фишки с покемонами");
            specifications.Luggage.Add("Чайный сервиз");
            specifications.Luggage.Add("Урна с прахом голубя");
            specifications.Luggage.Add("Упаковка печенек");
            specifications.Luggage.Add("Чупа-чупс с жвачкой");
            specifications.Luggage.Add("Холодильник");
            specifications.Luggage.Add("Перочинный нож");
            specifications.Luggage.Add("Кирка");
            specifications.Luggage.Add("Кулинарная книга");
            specifications.Luggage.Add("Спасательный круг");
            specifications.Luggage.Add("Туристическая палатка");
            specifications.Luggage.Add("Настенные часы");
            specifications.Luggage.Add("Компас");
            specifications.Luggage.Add("Диск с порно");
            specifications.Luggage.Add("Портфель с бытовой химией");
            specifications.Luggage.Add("Влажные салфетки");
            specifications.Luggage.Add("Пистолет с полной обоймой");
            specifications.Luggage.Add("ELFBAR на 1500 тяг");
            specifications.Luggage.Add("Ведро вишни");
            specifications.Luggage.Add("Упаковка рюмок");
            specifications.Luggage.Add("Карта звёзд");
            specifications.Luggage.Add("Карбюратор");
            specifications.Luggage.Add("Фитнес - браслет");
            specifications.Luggage.Add("Дрова");
            specifications.Luggage.Add("Набор инструментов");
            specifications.Luggage.Add("Лопата");
            specifications.Luggage.Add("Маникюрный набор");
            specifications.Luggage.Add("Лук(оружие)");
            specifications.Luggage.Add("Арболет");
            specifications.Luggage.Add("Водолазный костюм");
            specifications.Luggage.Add("Веревка 3м");
            specifications.Luggage.Add("Семена баклажанов");
            specifications.Luggage.Add("Огурец и помидорка");
            specifications.Luggage.Add("Плюшевый мишка");
            specifications.Luggage.Add("Макароны");
            specifications.Luggage.Add("Кастрюля");
            specifications.Luggage.Add("Зарядник для телефона");
            specifications.Luggage.Add("Ноутбук с зарядным устройством");
            specifications.Luggage.Add("Мангал");
            specifications.Luggage.Add("Топор");
            specifications.Luggage.Add("Зонт");
            specifications.Luggage.Add("Бутылка питьевой воды");
            specifications.Luggage.Add("Аптечка первой помощи");
            specifications.Luggage.Add("Кружка");
            specifications.Luggage.Add("Нож");
            specifications.Luggage.Add("Щупальце");
            specifications.Luggage.Add("Ведро");
            specifications.Luggage.Add("Глобус");
            specifications.Luggage.Add("Подушка");
            specifications.Luggage.Add("Табурет");
            specifications.Luggage.Add("Ложка");
            specifications.Luggage.Add("Алмаз");
            specifications.Luggage.Add("Клубок ниток");
            specifications.Luggage.Add("Зонт");
            specifications.Luggage.Add("Магнит");
            specifications.Luggage.Add("Наушники");
            specifications.Luggage.Add("Динамик");
            specifications.Luggage.Add("Флешка");
            specifications.Luggage.Add("Песочные часы");
            specifications.Luggage.Add("Рыболовный крючок");
            specifications.Luggage.Add("Саженец картошки");
            specifications.Luggage.Add("Банка с консервами");
            specifications.Luggage.Add("Фонарь");
            specifications.Luggage.Add("Катушка ниток");
            specifications.Luggage.Add("Теплая одежда");
            specifications.Luggage.Add("Капкан");
            specifications.Luggage.Add("Компас");
            specifications.Luggage.Add("Глазное яблоко");
            specifications.Luggage.Add("Рюкзак");
            specifications.Luggage.Add("Мегафон");
            specifications.Luggage.Add("Щит");
            specifications.Luggage.Add("Телескопическая дубинка");
            specifications.Luggage.Add("Осадной нож");
            specifications.Luggage.Add("Гантань");
            specifications.Luggage.Add("Августовка (сабля)");
            specifications.Luggage.Add("Цуруги (меч)");
            specifications.Luggage.Add("Бородовидный топор");
            specifications.Luggage.Add("Губная помада");
            specifications.Luggage.Add("Хрустальный череп");
            specifications.Luggage.Add("Чёрный мелок");
            specifications.Luggage.Add("Спрей от насекомых");
            specifications.Luggage.Add("Четырёхлистный клевер, засушенный в книге о манерах и этикете");
            specifications.Luggage.Add("Мумифицированная рука");
            specifications.Luggage.Add("Книга о восхождении и свержении легендарного героя, в которой нет последней главы");
            specifications.Luggage.Add("Пустая серебряная табакерка с надписью на поверхности «грёзы»");
            specifications.Luggage.Add("Серебряная ложка с выгравированной на ручке буквой «М»");
            specifications.Luggage.Add("Плитка мозаики с разноцветной глазированной поверхностью");
            specifications.Luggage.Add("30-граммовый кусочек неизвестного материала");
            specifications.Luggage.Add("Яичная скорлупа, разрисованная с жуткими подробностями сценами человеческих мук");
            specifications.Luggage.Add("Плитка мозаики с разноцветной глазированной поверхностью");
            specifications.Luggage.Add("Мешочек битого стекла, собрав кусочки которого можно разглядеть карту кладов");
            specifications.Luggage.Add("Небольшой идол, изображающий страшное чудовище, насылающий кошмары, когда вы спите рядом с ним");
            specifications.Luggage.Add("Игральные кости с черепом вместо 6");
            specifications.Luggage.Add("Механическая канарейка в гномьей лампе");
            specifications.Luggage.Add("Чучело совы со странными глазами, если их затронуть, то откроется тайник-чучело");
            specifications.Luggage.Add("Одеяние с сотней крохотных карманов");
            specifications.Luggage.Add("Рукоятка от сломанного меча");
            specifications.Luggage.Add("Дневник,написанный на неизвестном вам языке");
            specifications.Luggage.Add("Ложка с портретом старика");
            specifications.Luggage.Add("Бутылка, в которой лежит драгоценный камень, обросший караллами");
            specifications.Luggage.Add("Не поддающаяся расшифровке карта сокровищ");
            specifications.Luggage.Add("Серебряный череп размером с монету");
            specifications.Luggage.Add("Иголка, которая никогда не гнётся");
            specifications.Luggage.Add("Пустой флакон, пахнущий духами при открытии");
            specifications.Luggage.Add("Стеклянная сфера с водой, в которой плавает механическая золотая рыбка");
            specifications.Luggage.Add("Курительная трубка, из которой вылетают пузыри");
            specifications.Luggage.Add("Красивая дварфская брошь");
            specifications.Luggage.Add("Серебряная серьга в виде слезинки, сделанная из настоящей слезинки");
            specifications.Luggage.Add("Рожок из слоновой кости");
            specifications.Luggage.Add("Ночной колпак, дарующий приятные сны");
            specifications.Luggage.Add("Один костяной калтроп");
            specifications.Luggage.Add("Урна с прахом");
            specifications.Luggage.Add("Фигурка игрока, который её имеет");
            specifications.Luggage.Add("Деревянная нога");
            specifications.Luggage.Add("Огромная чешуйка, возможно, драконья");
            specifications.Luggage.Add("Крошечная музыкальная шкатулка гномьей работы, наигрывающая мелодию, напоминающую вам о детстве");
            specifications.Luggage.Add("Серебряный значок в форме пятиконечной звезды");
            specifications.Luggage.Add("Деревянная коробка с керамическим дном, в которой живёт червяк с двумя головами");
            specifications.Luggage.Add("Кусок камня, меняющий цвет, в зависимости от настроения владельца");
            specifications.Luggage.Add("Сосуд с кровью");
            specifications.Luggage.Add("Крохотный металлический краб или паук, который двигается, когда на него не смотрят");
            specifications.Luggage.Add("Пустая бутылка из-под вина с небольшой наклейкой «Винокурня Винного Волшебника, Красное драконье, 331422-В»");
            specifications.Luggage.Add("Фиолетовый носовой платок с вышитым именем великого архимага");
            specifications.Luggage.Add("Хорошо сохранившийся череп ворона");
            specifications.Luggage.Add("Камень с резным портретом ужасного лица");
            specifications.Luggage.Add("Два игрушечных солдатика, один без головы");
            specifications.Luggage.Add("Металлические знаки отличия древнего королевства");
            specifications.Luggage.Add("Стеклянная бутылка сала с этикеткой «Жир жирафа»");
            specifications.Luggage.Add("Крохотный серебряный колокольчик без язычка");
            specifications.Luggage.Add("Латунная сфера, покрытая странными рунами");
            specifications.Luggage.Add("Запаянная металлическая банка, в которой, судя по звукам, находится жидкость, песок, пауки или битое стекло (на ваш выбор)");
            specifications.Luggage.Add("Старая стеклянная шахматная фигура");
            specifications.Luggage.Add("Шестипалая перчатка");
            specifications.Luggage.Add("Древняя стрела");
            specifications.Luggage.Add("аптечка");
            specifications.Luggage.Add("беспроводная колонка");
            specifications.Luggage.Add("бладхаунд");
            specifications.Luggage.Add("будильник");
            specifications.Luggage.Add("бутылка шампанского");
            specifications.Luggage.Add("гаечный ключ");
            specifications.Luggage.Add("газовая горелка");
            specifications.Luggage.Add("гитара");
            specifications.Luggage.Add("грудной ребёнок");
            specifications.Luggage.Add("губная гармошка");
            specifications.Luggage.Add("дедовское ружьё");
            specifications.Luggage.Add("десять одноразовых медицинских масок");
            specifications.Luggage.Add("дневник выжившего");
            specifications.Luggage.Add("дублёнка");
            specifications.Luggage.Add("зажигалка");
            specifications.Luggage.Add("карманные часы");
            specifications.Luggage.Add("карта местности");
            specifications.Luggage.Add("кассеты с фильмами");
            specifications.Luggage.Add("книга по социологии");
            specifications.Luggage.Add("компас");
            specifications.Luggage.Add("консервы");
            specifications.Luggage.Add("коробка с боеприпасами");
            specifications.Luggage.Add("коробок спичек");
            specifications.Luggage.Add("косметическое зеркало");
            specifications.Luggage.Add("ледоруб и трос");
            specifications.Luggage.Add("лейка");
            specifications.Luggage.Add("лук и стрелы");
            specifications.Luggage.Add("молоток и гвозди");
            specifications.Luggage.Add("музыкальная шкатулка");
            specifications.Luggage.Add("набор для шитья");
            specifications.Luggage.Add("набор инструментов");
            specifications.Luggage.Add("набор кухонных инструментов");
            specifications.Luggage.Add("настольные игры");
            specifications.Luggage.Add("немецкая овчарка");
            specifications.Luggage.Add("немецкая овчарка");
            specifications.Luggage.Add("несколько чистых листов пергамента");
            specifications.Luggage.Add("ноутбук");
            specifications.Luggage.Add("открывалка");
            specifications.Luggage.Add("пачка сигарет");
            specifications.Luggage.Add("персидский кот");
            specifications.Luggage.Add("пневматический пистолет");
            specifications.Luggage.Add("презервативы");
            specifications.Luggage.Add("противогаз");
            specifications.Luggage.Add("пустая коробка");
            specifications.Luggage.Add("радио");
            specifications.Luggage.Add("рулоны туалетной бумаги");
            specifications.Luggage.Add("семена капусты");
            specifications.Luggage.Add("семена картофеля");
            specifications.Luggage.Add("семена моркови");
            specifications.Luggage.Add("семена пшеницы");
            specifications.Luggage.Add("сотовый телефон");
            specifications.Luggage.Add("стерильные одноразовые шприцы");
            specifications.Luggage.Add("стопка журналов для взрослых");
            specifications.Luggage.Add("телевизор");
            specifications.Luggage.Add("топор и веревка");
            specifications.Luggage.Add("три респираторные маски");
            specifications.Luggage.Add("флейта");
            specifications.Luggage.Add("фонарик и запасные батарейки");
            specifications.Luggage.Add("фотоаппарат");
            specifications.Luggage.Add("четыре рации");
            specifications.Luggage.Add("Бита");
            specifications.Luggage.Add("Гитара");
            specifications.Luggage.Add("Попугай Ара");
            specifications.Luggage.Add("Набор для игры в дартс");
            specifications.Luggage.Add("Карта местности");
            specifications.Luggage.Add("Книга советов по выживанию в лесу");
            specifications.Luggage.Add("Насос");
            specifications.Luggage.Add("Ласты и гарпун");
            specifications.Luggage.Add("Спиртовой нагревательный прибор");
            specifications.Luggage.Add("Ключи от магазина");
            specifications.Luggage.Add("Рыболовный чемоданчик");
            specifications.Luggage.Add("Кулинарная книга рецептов");
            specifications.Luggage.Add("Шпатель");
            specifications.Luggage.Add("Иголка с нитками(стерильные одноразовые хирургические)");
            specifications.Luggage.Add("Старые видеокассеты");
            specifications.Luggage.Add("Пачка пистолетных патронов");
            specifications.Luggage.Add("Чемоданчик с различными антибиотиками");
            specifications.Luggage.Add("Домашний халат");
            specifications.Luggage.Add("Арбалет");
            specifications.Luggage.Add("Паук-птицеед");
            specifications.Luggage.Add("Пустые гильзы");
            specifications.Luggage.Add("Коробка алкоголя");
            specifications.Luggage.Add("Скелет");
            specifications.Luggage.Add("Бронежилет");
            specifications.Luggage.Add("Топор");
            specifications.Luggage.Add("Квадрокоптер");
            specifications.Luggage.Add("Корм для попугаев");
            specifications.Luggage.Add("Набор таблеток от ВИЧ");
            specifications.Luggage.Add("Семена картошки");
            specifications.Luggage.Add("Сборник произведений 'Кобзарь'");
            specifications.Luggage.Add("Перцовый баллончик");
            specifications.Luggage.Add("Упаковка печенья");
            specifications.Luggage.Add("Семена помидоров");
            specifications.Luggage.Add("Сотовый телефон");
            specifications.Luggage.Add("Рюкзак битком набитый тушёнкой");
            specifications.Luggage.Add("Суперклей и проволока");
            specifications.Luggage.Add("Радиоприёмник");
            specifications.Luggage.Add("Изолента");
            specifications.Luggage.Add("Костюм хим-защиты");
            specifications.Luggage.Add("Автомат калашникова");
            specifications.Luggage.Add("Бинокль");
            specifications.Luggage.Add("Акваланг");
            specifications.Luggage.Add("Ящик с инструментами");
            specifications.Luggage.Add("Ручная змея");
            specifications.Luggage.Add("Пазлы");
            specifications.Luggage.Add("Непромокаемая обувь");
            specifications.Luggage.Add("Папка листов бумаги А4");
            specifications.Luggage.Add("Скотч и ножницы");
            specifications.Luggage.Add("Книги по похудению");
            specifications.Luggage.Add("Соли");
            specifications.Luggage.Add("Грудной ребенок");
            specifications.Luggage.Add("Карта местоположения важных стратегических и военных объектов");
            specifications.Luggage.Add("Блок сигарет");
            specifications.Luggage.Add("Книга про зомби");
            specifications.Luggage.Add("Спайсы и спиды");
            specifications.Luggage.Add("Набор первой помощи");
            specifications.Luggage.Add("Зонтик");
            specifications.Luggage.Add("Свечи и десять спичечных коробков");
            specifications.Luggage.Add("Охотничий нож");

        }
    }
}
