using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Bunker.Models.Init_Models
{
    class Init_Profession
    {
        private Specifications specifications;
        public Init_Profession(Specifications _specifications)
        {
            specifications = _specifications;
            Fill_Profession();
        }

        private void Fill_Profession()
        {
            specifications.Profession.Add("Военнослужащий");
            specifications.Profession.Add("Конвоир");
            specifications.Profession.Add("Пожарный");
            specifications.Profession.Add("Разведчик");
            specifications.Profession.Add("Спасатель");
            specifications.Profession.Add("Телохранитель");
            specifications.Profession.Add("Верстальщик");
            specifications.Profession.Add("Выпускающий редактор");
            specifications.Profession.Add("Дата - журналист");
            specifications.Profession.Add("Журналист");
            specifications.Profession.Add("Издатель");
            specifications.Profession.Add("Корректор");
            specifications.Profession.Add("Переплетчик");
            specifications.Profession.Add("Печатник");
            specifications.Profession.Add("Редактор");
            specifications.Profession.Add("Фальцовщик");
            specifications.Profession.Add("HTML - верстальщик");
            specifications.Profession.Add("SMM - менеджер");
            specifications.Profession.Add("UX - дизайнер");
            specifications.Profession.Add("Web - интегратор");
            specifications.Profession.Add("Администратор базы данных");
            specifications.Profession.Add("Администратор сайта");
            specifications.Profession.Add("Аналитик Big Data");
            specifications.Profession.Add("Блогер");
            specifications.Profession.Add("Блокчейн - разработчик");
            specifications.Profession.Add("Веб - дизайнер");
            specifications.Profession.Add("Диктор");
            specifications.Profession.Add("Контент - менеджер");
            specifications.Profession.Add("Копирайтер");
            specifications.Profession.Add("Радиоведущий");
            specifications.Profession.Add("Сетевой инженер");
            specifications.Profession.Add("Системный администратор");
            specifications.Profession.Add("Системный аналитик");
            specifications.Profession.Add("Специалист по информационной безопасности");
            specifications.Profession.Add("Спичрайтер");
            specifications.Profession.Add("Тележурналист");
            specifications.Profession.Add("Тестировщик");
            specifications.Profession.Add("Акушер");
            specifications.Profession.Add("Анестезиолог");
            specifications.Profession.Add("Врач скорой помощи");
            specifications.Profession.Add("Врач - диетолог");
            specifications.Profession.Add("Генетик");
            specifications.Profession.Add("Дерматолог");
            specifications.Profession.Add("Зубной техник");
            specifications.Profession.Add("Иммунолог");
            specifications.Profession.Add("Кардиолог");
            specifications.Profession.Add("Кардиохирург");
            specifications.Profession.Add("Косметолог");
            specifications.Profession.Add("Лаборант");
            specifications.Profession.Add("Логопед");
            specifications.Profession.Add("Массажист");
            specifications.Profession.Add("Медсестра");
            specifications.Profession.Add("Невропатолог");
            specifications.Profession.Add("Нейрохирург");
            specifications.Profession.Add("Онколог");
            specifications.Profession.Add("Офтальмолог");
            specifications.Profession.Add("Педиатр");
            specifications.Profession.Add("Психолог");
            specifications.Profession.Add("Психотерапевт");
            specifications.Profession.Add("Спортивный врач");
            specifications.Profession.Add("Стоматолог");
            specifications.Profession.Add("Терапевт");
            specifications.Profession.Add("Фармацевт");
            specifications.Profession.Add("Фельдшер");
            specifications.Profession.Add("Археолог");
            specifications.Profession.Add("Архивариус");
            specifications.Profession.Add("Астроном");
            specifications.Profession.Add("Библиограф");
            specifications.Profession.Add("Биоинженер");
            specifications.Profession.Add("Биолог");
            specifications.Profession.Add("Биохимик");
            specifications.Profession.Add("Ботаник");
            specifications.Profession.Add("Вирусолог");
            specifications.Profession.Add("Востоковед");
            specifications.Profession.Add("Генный инженер");
            specifications.Profession.Add("Геолог");
            specifications.Profession.Add("Египтолог");
            specifications.Profession.Add("Искусствовед");
            specifications.Profession.Add("Историк");
            specifications.Profession.Add("Ихтиолог");
            specifications.Profession.Add("Конструктор");
            specifications.Profession.Add("Культуролог");
            specifications.Profession.Add("Лингвист");
            specifications.Profession.Add("Математик");
            specifications.Profession.Add("Метеоролог");
            specifications.Profession.Add("Микробиолог");
            specifications.Profession.Add("Наноинженер");
            specifications.Profession.Add("Нанотехнолог");
            specifications.Profession.Add("Орнитолог");
            specifications.Profession.Add("Палеонтолог");
            specifications.Profession.Add("Политолог");
            specifications.Profession.Add("Политтехнолог");
            specifications.Profession.Add("Почвовед");
            specifications.Profession.Add("Религиовед");
            specifications.Profession.Add("Социолог");
            specifications.Profession.Add("Философ");
            specifications.Profession.Add("Химик");
            specifications.Profession.Add("Эколог");
            specifications.Profession.Add("Этнограф");
            specifications.Profession.Add("Воспитатель");
            specifications.Profession.Add("Дефектолог");
            specifications.Profession.Add("Кинолог");
            specifications.Profession.Add("Педагог");
            specifications.Profession.Add("Преподаватель");
            specifications.Profession.Add("Ректор");
            specifications.Profession.Add("Сурдопедагог");
            specifications.Profession.Add("Тифлопедагог");
            specifications.Profession.Add("Учитель");
            specifications.Profession.Add("Хореограф");
            specifications.Profession.Add("Булочник");
            specifications.Profession.Add("Винодел");
            specifications.Profession.Add("Дегустатор");
            specifications.Profession.Add("Диетолог");
            specifications.Profession.Add("Месильщик");
            specifications.Profession.Add("Мясник");
            specifications.Profession.Add("Пекарь");
            specifications.Profession.Add("Повар");
            specifications.Profession.Add("Повар - кондитер");
            specifications.Profession.Add("Шеф - повар");
            specifications.Profession.Add("Промышленный альпинист");
            specifications.Profession.Add("Агроном");
            specifications.Profession.Add("Ветеринар");
            specifications.Profession.Add("Доярка");
            specifications.Profession.Add("Животновод");
            specifications.Profession.Add("Охотник");
            specifications.Profession.Add("Пчеловод");
            specifications.Profession.Add("Садовник");
            specifications.Profession.Add("Тракторист");
            specifications.Profession.Add("Фермер");
            specifications.Profession.Add("Агент по туризму");
            specifications.Profession.Add("Администратор гостиницы");
            specifications.Profession.Add("Администратор ресторана");
            specifications.Profession.Add("Бармен");
            specifications.Profession.Add("Библиотекарь");
            specifications.Profession.Add("Визажист");
            specifications.Profession.Add("Гид - переводчик");
            specifications.Profession.Add("Грузчик");
            specifications.Profession.Add("Дворник");
            specifications.Profession.Add("Ивент - менеджер");
            specifications.Profession.Add("Кладовщик");
            specifications.Profession.Add("Консультант телефона доверия");
            specifications.Profession.Add("Мастер маникюра");
            specifications.Profession.Add("Мусорщик");
            specifications.Profession.Add("Оператор call - центра");
            specifications.Profession.Add("Официант");
            specifications.Profession.Add("Парикмахер");
            specifications.Profession.Add("Портье");
            specifications.Profession.Add("Почтальон");
            specifications.Profession.Add("Риелтор");
            specifications.Profession.Add("Страховой агент");
            specifications.Profession.Add("Флорист");
            specifications.Profession.Add("Экскурсовод");
            specifications.Profession.Add("Спортивный инструктор по видам спорта");
            specifications.Profession.Add("Спортивный тренер");
            specifications.Profession.Add("Спортсмен");
            specifications.Profession.Add("Актер");
            specifications.Profession.Add("Аниматор");
            specifications.Profession.Add("Арт - директор");
            specifications.Profession.Add("Архитектор");
            specifications.Profession.Add("Бренд - дизайнер");
            specifications.Profession.Add("Диджей");
            specifications.Profession.Add("Дизайнер интерьера");
            specifications.Profession.Add("Дизайнер - модельер");
            specifications.Profession.Add("Дирижер");
            specifications.Profession.Add("Звукорежиссер");
            specifications.Profession.Add("Иллюстратор");
            specifications.Profession.Add("Каскадер");
            specifications.Profession.Add("Киномеханик");
            specifications.Profession.Add("Кинооператор");
            specifications.Profession.Add("Кинорежиссер");
            specifications.Profession.Add("Композитор");
            specifications.Profession.Add("Критик");
            specifications.Profession.Add("Ландшафтный дизайнер");
            specifications.Profession.Add("Мультипликатор");
            specifications.Profession.Add("Переводчик");
            specifications.Profession.Add("Писатель");
            specifications.Profession.Add("Продюсер");
            specifications.Profession.Add("Режиссер");
            specifications.Profession.Add("Реставратор");
            specifications.Profession.Add("Скульптор");
            specifications.Profession.Add("Стилист");
            specifications.Profession.Add("Сценарист");
            specifications.Profession.Add("Татуировщик");
            specifications.Profession.Add("Технический писатель");
            specifications.Profession.Add("Урбанист");
            specifications.Profession.Add("Фотограф");
            specifications.Profession.Add("Фотомодель");
            specifications.Profession.Add("Ювелир");
            specifications.Profession.Add("Автомеханик");
            specifications.Profession.Add("Водолаз");
            specifications.Profession.Add("Геодезист");
            specifications.Profession.Add("Драпировщик");
            specifications.Profession.Add("Звукооператор");
            specifications.Profession.Add("Инженер по охране труда и технике безопасности");
            specifications.Profession.Add("Каменщик");
            specifications.Profession.Add("Картограф");
            specifications.Profession.Add("Крановщик");
            specifications.Profession.Add("Краснодеревщик");
            specifications.Profession.Add("Кровельщик");
            specifications.Profession.Add("Литейщик");
            specifications.Profession.Add("Маляр");
            specifications.Profession.Add("Маркшейдер");
            specifications.Profession.Add("Металлург");
            specifications.Profession.Add("Облицовщик");
            specifications.Profession.Add("Отделочник");
            specifications.Profession.Add("Плотник");
            specifications.Profession.Add("Прораб");
            specifications.Profession.Add("Слесарь");
            specifications.Profession.Add("Столяр");
            specifications.Profession.Add("Строитель");
            specifications.Profession.Add("Технолог");
            specifications.Profession.Add("Часовщик");
            specifications.Profession.Add("Электрик");
            specifications.Profession.Add("Авиадиспетчер");
            specifications.Profession.Add("Автогонщик");
            specifications.Profession.Add("Бортинженер");
            specifications.Profession.Add("Бортпроводник");
            specifications.Profession.Add("Космонавт");
            specifications.Profession.Add("Летчик");
            specifications.Profession.Add("Логист");
            specifications.Profession.Add("Лоцман");
            specifications.Profession.Add("Машинист");
            specifications.Profession.Add("Стюардесса");
            specifications.Profession.Add("Таксист");
            specifications.Profession.Add("Штурман");
            specifications.Profession.Add("Экспедитор");
            specifications.Profession.Add("PR - менеджер");
            specifications.Profession.Add("Product - менеджер");
            specifications.Profession.Add("Аудитор");
            specifications.Profession.Add("Банкир");
            specifications.Profession.Add("Бизнес - тренер");
            specifications.Profession.Add("Бренд - менеджер");
            specifications.Profession.Add("Брокер");
            specifications.Profession.Add("Бухгалтер");
            specifications.Profession.Add("Инкассатор");
            specifications.Profession.Add("Кризис - менеджер");
            specifications.Profession.Add("Лоббист");
            specifications.Profession.Add("Маркетолог");
            specifications.Profession.Add("Менеджер");
            specifications.Profession.Add("Менеджер по логистике");
            specifications.Profession.Add("Менеджер по персоналу");
            specifications.Profession.Add("Мерчендайзер");
            specifications.Profession.Add("Налоговый инспектор");
            specifications.Profession.Add("Офис - менеджер");
            specifications.Profession.Add("Оценщик");
            specifications.Profession.Add("Продакт - менеджер");
            specifications.Profession.Add("Секретарь");
            specifications.Profession.Add("Статистик");
            specifications.Profession.Add("Супервайзер");
            specifications.Profession.Add("Товаровед");
            specifications.Profession.Add("Торговый представитель");
            specifications.Profession.Add("Трейдер");
            specifications.Profession.Add("Финансист");
            specifications.Profession.Add("Финансовый аналитик");
            specifications.Profession.Add("Экономист");
            specifications.Profession.Add("Адвокат");
            specifications.Profession.Add("Делопроизводитель");
            specifications.Profession.Add("Детектив");
            specifications.Profession.Add("Дипломат");
            specifications.Profession.Add("Инспектор по охране труда");
            specifications.Profession.Add("Нотариус");
            specifications.Profession.Add("Полицейский");
            specifications.Profession.Add("Правовед");
            specifications.Profession.Add("Прокурор");
            specifications.Profession.Add("Следователь");
            specifications.Profession.Add("Судебный пристав");
            specifications.Profession.Add("Судья");
            specifications.Profession.Add("Тюремный надзиратель");
            specifications.Profession.Add("Юрист");
            specifications.Profession.Add("Вебкам модель");
        }
    }
}
