using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Bunker.Models.Init_Models
{
    class Init_Devices
    {
        Specifications specifications;
        public Init_Devices(Specifications _specifications)
        {
            specifications = _specifications;
            Fill_Devices();
        }

        private void Fill_Devices()
        {
            specifications.Devices.Add("Аптечка(базовая)");
            specifications.Devices.Add("Семена пшеницы и пакет почвы");
            specifications.Devices.Add("Гитара и комплект струн");
            specifications.Devices.Add("Тёплый комплект одежды");
            specifications.Devices.Add("Инкубатор с яйцами");
            specifications.Devices.Add("Счетчик гейгера");
            specifications.Devices.Add("Коробка с противогазами от радиации");
            specifications.Devices.Add("Книги по технологии строительства");
            specifications.Devices.Add("Бионические протезы(2 штуки)");
            specifications.Devices.Add("Керосиновые лампы и топливо");
            specifications.Devices.Add("Тетради и ручки");
            specifications.Devices.Add("Игровая приставка");
            specifications.Devices.Add("Книги по психологии");
            specifications.Devices.Add("Книги по урологии");
            specifications.Devices.Add("Книги по гинекологии");
            specifications.Devices.Add("Несколько охотничьих ножей");
            specifications.Devices.Add("Беговая дорожка");
            specifications.Devices.Add("Радио");
            specifications.Devices.Add("Семена овощей");
            specifications.Devices.Add("Семена фруктов");
            specifications.Devices.Add("Книга по ремонту техники");
            specifications.Devices.Add("Кухонные ножи");
            specifications.Devices.Add("Ружье и патроны");
            specifications.Devices.Add("Ингалятор");
            specifications.Devices.Add("Скрипка");
            specifications.Devices.Add("Топографическая карта местности");
            specifications.Devices.Add("Книга рецептов");
            specifications.Devices.Add("Книги по очистке воды");
            specifications.Devices.Add("Аптечка(базовая)");
            specifications.Devices.Add("Мужские журналы");
            specifications.Devices.Add("Женские журналы");
            specifications.Devices.Add("Радиационный защитный костюм");
            specifications.Devices.Add("Туристическое снаряжение (Спальный мешок; палатка; котелок)");
            specifications.Devices.Add("Медицинский спирт");
            specifications.Devices.Add("Патроны (Пистолет)");
            specifications.Devices.Add("Серп");
            specifications.Devices.Add("Акваланг");
            specifications.Devices.Add("Водка");
            specifications.Devices.Add("Мешок с землей");
            specifications.Devices.Add("Граната");
            specifications.Devices.Add("Набор колб");
            specifications.Devices.Add("Лазерный прицел");
            specifications.Devices.Add("Мотыга");
            specifications.Devices.Add("3кг Муки");
            specifications.Devices.Add("Телевизор");
            specifications.Devices.Add("Дозиметр");
            specifications.Devices.Add("Нитки");
            specifications.Devices.Add("Ящик консервов");
            specifications.Devices.Add("Резиновые перчатки и сапоги");
            specifications.Devices.Add("Спички");
            specifications.Devices.Add("Камуфляжный костюм");
            specifications.Devices.Add("Фильтр для очистки воды");
            specifications.Devices.Add("10кг зерна");
            specifications.Devices.Add("Бензопила");
            specifications.Devices.Add("Капкан");
            specifications.Devices.Add("Перекись водорода");
            specifications.Devices.Add("Дрон с камерой");
            specifications.Devices.Add("Пачка семян");
            specifications.Devices.Add("Рюкзак");
            specifications.Devices.Add("Уголь");
            specifications.Devices.Add("Дымовая граната");
            specifications.Devices.Add("Гаечный ключ");
            specifications.Devices.Add("Ящик пива");
            specifications.Devices.Add("Мотыга");
            specifications.Devices.Add("Палатка");
            specifications.Devices.Add("Лопата");
            specifications.Devices.Add("Шприцы");
            specifications.Devices.Add("Микроскоп");
            specifications.Devices.Add("Камера видеонаблюдения");
            specifications.Devices.Add("Нож");
            specifications.Devices.Add("Балон с газом");
            specifications.Devices.Add("Ружье");
            specifications.Devices.Add("Гвозди");
            specifications.Devices.Add("Рубанок");
            specifications.Devices.Add("Медицинские перчатки");
            specifications.Devices.Add("Сигнальный пистолет (1 патрон)");
            specifications.Devices.Add("Зелёнка");
            specifications.Devices.Add("Строительные перчатки");
            specifications.Devices.Add("Противогаз");
            specifications.Devices.Add("Дрова");
            specifications.Devices.Add("Туалетная бумага");
            specifications.Devices.Add("Отмычки");
            specifications.Devices.Add("Книги");
            specifications.Devices.Add("Фонарики");
            specifications.Devices.Add("Шокер");
            specifications.Devices.Add("Рыболовная сеть");
            specifications.Devices.Add("Пила");
            specifications.Devices.Add("Куртки");
            specifications.Devices.Add("Провод(3м)");
            specifications.Devices.Add("Удочка");
            specifications.Devices.Add("Средство от насекомых");
            specifications.Devices.Add("Средство от грызунов");
            specifications.Devices.Add("Бита");
            specifications.Devices.Add("Бензиновый генератор");
            specifications.Devices.Add("Бензин (1 л)");
            specifications.Devices.Add("Лазерная указка");
            specifications.Devices.Add("Курица");
            specifications.Devices.Add("Рация (2шт)");
            specifications.Devices.Add("Канистра с бензином");
            specifications.Devices.Add("Веревка (5 м)");
            specifications.Devices.Add("Средство от комаров");
            specifications.Devices.Add("Доски (15 шт)");
            specifications.Devices.Add("Доски (5 шт)");
            specifications.Devices.Add("Банка томатного супа (можно хранить до 5 лет)");
            specifications.Devices.Add("Топор");
            specifications.Devices.Add("Снайперская винтовка (без патрон)");
            specifications.Devices.Add("Патроны (Ружье)");
            specifications.Devices.Add("Патроны (Автомат)");
            specifications.Devices.Add("Патроны (Снайперская винтовка)");
            specifications.Devices.Add("Карта местности");
            specifications.Devices.Add("Скотч");
            specifications.Devices.Add("Тепловизор");
            specifications.Devices.Add("Москитная сетка");
            specifications.Devices.Add("Солнцезащитные очки");
            specifications.Devices.Add("Канистра воды (10 л)");
            specifications.Devices.Add("Канистра воды (50 л)");
            specifications.Devices.Add("Канистра воды (5 л)");
            specifications.Devices.Add("Наручные часы");
            specifications.Devices.Add("Глушитель на оружие (Пистолет)");
            specifications.Devices.Add("Глушитель на оружие (Ружье)");
            specifications.Devices.Add("Глушитель на оружие (Автомат)");
            specifications.Devices.Add("Глушитель на оружие (Снайперская винтовка)");
            specifications.Devices.Add("Жидкость для розжига");
            specifications.Devices.Add("Чертёж бункера (имеется секретная комната)");
            specifications.Devices.Add("Пищевая сода");
            specifications.Devices.Add("Набор юного химика");
            specifications.Devices.Add("Набор зимикатов");
            specifications.Devices.Add("Набор инструментов для работы по дереву");
            specifications.Devices.Add("Набор инструментов для работы по металлу");
            specifications.Devices.Add("Мышеловки");
            specifications.Devices.Add("Пистолет (без патронов)");
            specifications.Devices.Add("Ружье (без патронов)");
            specifications.Devices.Add("Автомат (без патронов)");
            specifications.Devices.Add("Леска");
            specifications.Devices.Add("Лом");
            specifications.Devices.Add("Бинты");
            specifications.Devices.Add("Вата");
            specifications.Devices.Add("Собака");
            specifications.Devices.Add("Кот");
            specifications.Devices.Add("Уксус");
            specifications.Devices.Add("Сухое мясо");
            specifications.Devices.Add("Кастет");
            specifications.Devices.Add("Йод");
            specifications.Devices.Add("Таблетки от боли в животе");
            specifications.Devices.Add("Мешки с песком");
            specifications.Devices.Add("Пособие по основам ремонта");
            specifications.Devices.Add("Гантели");
            specifications.Devices.Add("Книга по животноводству");
            specifications.Devices.Add("Энциклопедия животных и растений");
            specifications.Devices.Add("Дихлофоз");
            specifications.Devices.Add("Респираторы");
            specifications.Devices.Add("Хирургический набор");
            specifications.Devices.Add("Книга по растеневодству");
            specifications.Devices.Add("Корм для животных");
            specifications.Devices.Add("Зарядка для телефона");
            specifications.Devices.Add("Канистры топлива");
            specifications.Devices.Add("Исследовательский дрон");
            specifications.Devices.Add("Пахучая приманка для зверей");
            specifications.Devices.Add("Мультиварка");
            specifications.Devices.Add("Нет");
            specifications.Devices.Add("Нет");
            specifications.Devices.Add("Нет");
        }
    }
}
